apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress-tutorial # Match with namespace
spec:
  type: NodePort
  ports:
  - port: 80 # Port that publicly exposed to internet
    targetPort: 80 # Match with MARK C.1
    protocol: TCP
    nodePort: 30080 # Optional: specify a static NodePort if needed
  selector:
    app: wordpress # Match with MARK C
